// Generated by SnapshotCodeGenerator

export interface StabilityPoolStateSnapshot {
  collateralLoss: bigint;
  lastSBRRewardDistributedTime: bigint;
  minimumScalingFactor: bigint;
  precision: bigint;
  rewardLoss: bigint;
  rewardSenderActive: boolean;
  sbrDistributionRate: bigint;
  sbrRewardDistributionEndTime: bigint;
  sbrRewardDistributionStatus: number;
  sbrRewardLoss: bigint;
  stakeResetCount: bigint;
  stakeScalingFactor: bigint;
  totalCollateralPerToken: bigint;
  totalRewardPerToken: bigint;
  totalSbrRewardPerToken: bigint;
  totalStakedRaw: bigint;
  stakeResetSnapshots: {
    scalingFactor: bigint;
    totalRewardPerToken: bigint;
    totalCollateralPerToken: bigint;
    totalSBRRewardPerToken: bigint;
  }[];
}

export interface StabilityPoolUserSnapshot {
  userInfo: {
    stake: bigint;
    rewardSnapshot: bigint;
    collateralSnapshot: bigint;
    cumulativeProductScalingFactor: bigint;
    stakeResetCount: bigint;
  };
  pendingReward: bigint;
  pendingCollateral: bigint;
  sbrRewardSnapshot: {
    rewardSnapshot: bigint;
    status: number;
  };
}

export interface StableBaseCDPState {
  mode: number;
  collateralLoss: bigint;
  cumulativeCollateralPerUnitCollateral: bigint;
  cumulativeDebtPerUnitCollateral: bigint;
  debtLoss: bigint;
  name: string;
  totalCollateral: bigint;
  totalDebt: bigint;
  symbol: string;
  sbrStakingPoolCanReceiveRewards: boolean;
  stabilityPoolCanReceiveRewards: boolean;
  liquidationSnapshots: {[safeId: string]: { collateralPerCollateralSnapshot: bigint; debtPerCollateralSnapshot: bigint; }};
  safes: {[safeId: string]: { collateralAmount: bigint; borrowedAmount: bigint; weight: bigint; totalBorrowedAmount: bigint; feePaid: bigint; }};
}

export interface StableBaseCDPUserState {
  balanceOf: bigint;
  ownerOf: string;
  getApproved: string;
  isApprovedForAll: boolean;
  getInactiveDebtAndCollateral: { collateral: bigint; debt: bigint; };
  tokenURI: string;
}

