// Generated by SnapshotCodeGenerator

import { Snapshot, SnapshotProvider } from "@svylabs/ilumina";
import { Contract, HardhatEthersSigner } from "ethers";
import { Actor } from "@svylabs/ilumina";


import { takestabilityPoolContractSnapshot } from "./stabilityPool_snapshot.ts";

import { takestableBaseCDPContractSnapshot } from "./stableBaseCDP_snapshot.ts";


export interface ContractSnapshot {

    stabilityPool: StabilityPoolSnapshot;

    stableBaseCDP: StableBaseCDPSnapshot;

}

export class ContractSnapshotProvider implements SnapshotProvider {
    private contracts: Record<string, Contract>;
    private actors: Actor[];

    constructor(contracts: Record<string, Contract>, actors: Actor[]) {
        this.contracts = contracts;
        this.actors = actors;
    }

    async snapshot(): Promise<Snapshot> {   
        const snapshot: Snapshot = {
            contractSnapshot: {},
            accountSnapshot: {}
        };
        const contractSnapshot = {};
        
        contractSnapshot["stabilityPool"] = await takestabilityPoolContractSnapshot(this.contracts.stabilityPool, this.actors);
        
        contractSnapshot["stableBaseCDP"] = await takestableBaseCDPContractSnapshot(this.contracts.stableBaseCDP, this.actors);
        
        snapshot.contractSnapshot = contractSnapshot;
        for (const actor of this.actors) {
            snapshot.accountSnapshot[actor.account.address] = await (actor.account.value as HardhatEthersSigner).getBalance();
        }
        return snapshot;
    }
}