// Generated by SnapshotCodeGenerator

import { ethers } from 'ethers';
import { Actor, Snapshot } from '@svylabs/ilumina';
import { StableBaseCDPSnapshot } from './snapshot_interfaces';

/**
 * Takes a snapshot of StableBaseCDP state
 * @param contract - ethers.Contract instance
 * @param actors - Array of Actor objects containing identifiers
 * @returns Promise returning the interface StableBaseCDPSnapshot
 */
export async function takestableBaseCDPContractSnapshot(contract: ethers.Contract, actors: Actor[]): Promise<StableBaseCDPSnapshot> {
  try {
    const balances: { [accountAddress: string]: bigint } = {};
    const approvals: { [safeId: bigint]: string } = {};
    const inactiveDebtAndCollateral: { [safeId: bigint]: [bigint, bigint] } = {};
    const approvalForAll: { [owner: string]: { [operator: string]: boolean } } = {};
    const owners: { [safeId: bigint]: string } = {};
    const safes: { [safeId: bigint]: { collateralAmount: bigint; borrowedAmount: bigint; weight: bigint; totalBorrowedAmount: bigint; feePaid: bigint } } = {};
    const tokenURIs: { [safeId: bigint]: string } = {};
    const liquidationSnapshots: { [safeId: bigint]: { collateralPerCollateralSnapshot: bigint, debtPerCollateralSnapshot: bigint } } = {};

    // Fetch global contract state
    const collateralLoss = BigInt(await contract.collateralLoss());
    const cumulativeCollateralPerUnitCollateral = BigInt(await contract.cumulativeCollateralPerUnitCollateral());
    const cumulativeDebtPerUnitCollateral = BigInt(await contract.cumulativeDebtPerUnitCollateral());
    const debtLoss = BigInt(await contract.debtLoss());
    const mode = Number(await contract.mode());
    const name = await contract.name();
    const sbrStakingPoolCanReceiveRewards = await contract.sbrStakingPoolCanReceiveRewards();
    const stabilityPoolCanReceiveRewards = await contract.stabilityPoolCanReceiveRewards();
    const symbol = await contract.symbol();
    const totalCollateral = BigInt(await contract.totalCollateral());
    const totalDebt = BigInt(await contract.totalDebt());

    // Iterate over actors to fetch user-specific and safe-specific data
    for (const actor of actors) {
      const accountAddress = actor.accountAddress;

      // Fetch Balance for each account address
      balances[accountAddress] = BigInt(await contract.balanceOf(accountAddress));

      if (actor.identifiers['_safeId']) {
        // Handle single _safeId or array of _safeIds
        const safeIds = Array.isArray(actor.identifiers['_safeId']) ? actor.identifiers['_safeId'] : [actor.identifiers['_safeId']];

        for (const safeId of safeIds) {
          const _safeId = BigInt(safeId);

          // Fetch Approval for each _safeId
          approvals[_safeId] = await contract.getApproved(_safeId);

          // Fetch InactiveDebtAndCollateral for each _safeId
          const [inactiveDebt, inactiveCollateral] = await contract.getInactiveDebtAndCollateral(_safeId);
          inactiveDebtAndCollateral[_safeId] = [BigInt(inactiveDebt), BigInt(inactiveCollateral)];

          // Fetch Owner for each _safeId
          owners[_safeId] = await contract.ownerOf(_safeId);

          // Fetch Safe data for each _safeId
          const safe = await contract.safes(_safeId);
          safes[_safeId] = { collateralAmount: BigInt(safe.collateralAmount), borrowedAmount: BigInt(safe.borrowedAmount), weight: BigInt(safe.weight), totalBorrowedAmount: BigInt(safe.totalBorrowedAmount), feePaid: BigInt(safe.feePaid) };

          // Fetch TokenURI for each _safeId
          tokenURIs[_safeId] = await contract.tokenURI(_safeId);

          // Fetch LiquidationSnapshots for each _safeId
          const liquidationSnapshot = await contract.liquidationSnapshots(_safeId);
          liquidationSnapshots[_safeId] = { collateralPerCollateralSnapshot: BigInt(liquidationSnapshot.collateralPerCollateralSnapshot), debtPerCollateralSnapshot: BigInt(liquidationSnapshot.debtPerCollateralSnapshot) };
        }
      }

      // Fetch ApprovalForAll for each account address pair
      for (const otherActor of actors) {
          const operatorAddress = otherActor.accountAddress;
          if (!approvalForAll[accountAddress]) {
              approvalForAll[accountAddress] = {};
          }
          approvalForAll[accountAddress][operatorAddress] = await contract.isApprovedForAll(accountAddress, operatorAddress);
      }
    }

    const snapshot: StableBaseCDPSnapshot = {
      balances,
      collateralLoss,
      cumulativeCollateralPerUnitCollateral,
      cumulativeDebtPerUnitCollateral,
      debtLoss,
      approvals,
      inactiveDebtAndCollateral,
      approvalForAll,
      mode,
      name,
      owners,
      safes,
      sbrStakingPoolCanReceiveRewards,
      stabilityPoolCanReceiveRewards,
      symbol,
      tokenURIs,
      totalCollateral,
      totalDebt,
      liquidationSnapshots
    };

    return snapshot;
  } catch (error) {
    console.error('Error taking StableBaseCDP snapshot:', error);
    throw error;
  }
}
